# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Taleoop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Taleoop
  
  
  
  pod 'ActiveLabel'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'MJExtension'
  
  
  pod 'Bugly'
  pod 'SVGAPlayer'
  pod 'Protobuf', '~> 3.4'
  pod 'YYEVA'
  pod 'SSZipArchive'
  pod 'AgoraRtm', '2.2.2', :subspecs => ['RtmKit']
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
  end
  
  
end


